//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pab.LoginCourt.TaskScheduler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Analytics_NewEntities : DbContext
    {
        public Analytics_NewEntities()
            : base("name=Analytics_NewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CourtSetting> CourtSettings { get; set; }
        public virtual DbSet<CourtSiteInfo> CourtSiteInfoes { get; set; }
        public virtual DbSet<CourtUser> CourtUsers { get; set; }
    }
}
