//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourtSiteInfo
    {
        public int Id { get; set; }
        public Nullable<int> CourtUserId { get; set; }
        public string TabName { get; set; }
        public Nullable<System.DateTime> CourtDate { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
    }
}
