//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobWork
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A6183C_testbazaEntities : DbContext
    {
        public DB_A6183C_testbazaEntities()
            : base("name=DB_A6183C_testbazaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CourtSiteInfo> CourtSiteInfoes { get; set; }
        public virtual DbSet<CourtUser> CourtUsers { get; set; }
    }
}
