//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAB.LoginInCourt
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourtSetting
    {
        public int Id { get; set; }
        public Nullable<int> RandomStart { get; set; }
        public Nullable<int> RandomEnd { get; set; }
        public Nullable<System.TimeSpan> ProgramExitTime { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
    }
}
