//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAB.LoginInCourt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Analytics_NewEntities : DbContext
    {
        public Analytics_NewEntities()
            : base("name=Analytics_NewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CourtUser> CourtUsers { get; set; }
        public DbSet<CourtSiteInfo> CourtSiteInfoes { get; set; }
        public DbSet<CourtSetting> CourtSettings { get; set; }
    }
}
